const fs = require('fs');

const i18nPath = 'resources/js/services/i18n.js';
let content = fs.readFileSync(i18nPath, 'utf8');

// The new comprehensive dictionary entries
const newEntries = [
    // 1. NG REPORT (User Screenshot specifics)
    ['Antrean Laporan NG', 'NG報告受付・入力待ち'],
    ['Status Input Detail', '入力進捗ステータス'],
    ['Total Target NG:', '目標NG数合計:'],
    ['Total Target NG', '目標NG数合計'],
    ['Sudah Lengkap:', '入力完了:'],
    ['Sudah Lengkap', '入力完了'],
    ['Komponen Wajib (OEE)', '主要部品 (OEE対象)'],
    ['Pelengkap (Non-OEE)', '付属部品 (非OEE)'],
    ['Pelengkap (non-OEE)', '付属部品 (非OEE)'],
    ['non-OEE', '非OEE'],
    ['Pcs non-OEE', '個 (非OEE)'],
    ['(20 Pcs non-OEE)', '(20個 非OEE)'],
    ['Daftar Antrean Laporan Harian yang Memiliki Reject / Defect', '品質不良・NG発生日報一覧 (要内訳入力)'],
    ['Hanya menampilkan transaksi harian dengan Total NG > 0 yang memerlukan rincian komponen', '内訳登録が必要な不良数(Total NG > 0)の生産実績のみを表示しています'],
    ['Hanya menampilkan transaksi harian dengan Total NG &gt; 0 yang memerlukan rincian komponen', '内訳登録が必要な不良数(Total NG > 0)の生産実績のみを表示しています'],
    ['Cari Lini, Mesin, SKU, Produk...', 'ライン、設備、品番(SKU)、製品名で検索...'],
    ['Total Terdata:', '登録済合計:'],
    ['Total Terdata', '登録済合計'],
    ['Belum dirinci', '未登録'],
    ['Belum diisi', '未入力'],
    ['Belum Diisi', '未入力'],
    ['Perlu Input', '要入力'],
    ['Input Detail', '内訳入力'],
    ['Edit Detail', '内訳編集'],
    ['Lengkap', '登録完了'],
    ['Selisih', '差異'],
    ['Semua Status', '全ステータス'],
    ['Selesai Terisi', '入力完了'],
    ['Tidak ada antrean laporan NG', 'NG報告の待機データはありません'],
    ['Semua laporan harian pada filter ini memiliki 0 reject atau detail NG telah selesai diinput.', '対象期間の全日報で不良ゼロ、またはNG内訳の登録がすべて完了しています。'],
    ['Semua Lini Produksi', '全生産ライン'],
    ['Semua Shift', '全直 (シフト)'],
    ['Rincian Komponen Wajib (OEE)', '主要部品内訳 (OEE)'],
    ['Status Input', '入力進捗状態'],
    ['2 Laporan', '2件'],
    ['1 Laporan', '1件'],
    ['1 Pending', '1件 未入力'],
    ['Pending', '未入力'],

    // 2. TABLE HEADERS ACROSS ALL VIEWS
    ['Tanggal & Shift', '生産日・直'],
    ['Lini & Mesin', 'ライン・設備'],
    ['Produk - SKU', '製品名・型番 (SKU)'],
    ['Total Output', '総生産数'],
    ['Target NG', '目標NG数'],
    ['Shift Name', '直名称'],
    ['OEE %', 'OEE効率 (%)'],
    ['Penyebab Defect / Remark', '不良要因・備考'],
    ['Bagian NG (Section)', '不良発生部位'],
    ['Reject Qty', '不良数 (NG)'],
    ['Kumulatif (%)', '累積比率 (%)'],
    ['Klasifikasi', '区分・分類'],
    ['Line ID & Name', 'ラインID・名称'],
    ['Machine & Produk - SKU', '設備・製品型番 (SKU)'],
    ['Planned (Min)', '計画稼働 (分)'],
    ['Down (Min)', '停止時間 (分)'],
    ['Avail (%)', '時間稼働率 (%)'],
    ['Target Speed', '基準速度'],
    ['Output (Pcs)', '出来高 (個)'],
    ['Perf (%)', '性能稼働率 (%)'],
    ['Defect (Rej+Scrap)', '不良数 (NG+損)'],
    ['Quality (%)', '良品率 (%)'],
    ['Type Produk (SKU)', '製品型番 (SKU)'],
    ['OK (Pcs)', '良品数 (OK)'],
    ['Total NG', '総不良数'],
    ['Defect %', '不良率 (%)'],
    ['Wajib OEE (Assy/Rod/Cap)', '主要部品 (Assy/Rod/Cap)'],
    ['Pelengkap (Bolt/Bush/Nut/Pin)', '締結部品 (Bolt/Bush/Nut/Pin)'],
    ['Kategori & Masalah Defect', '不良分類・現象'],
    ['Tanggal & Waktu', '発生日時'],
    ['Gejala & Root Cause Trouble', '異常現象及び根本要因'],
    ['PIC / Tim', '担当 / 班'],
    ['Parameter Metrik', '評価指標パラメータ'],
    ['Target Standar', '基準目標値'],
    ['Pencapaian Aktual', '実績値'],
    ['Deviasi', '差異・乖離'],
    ['Kategori Six Big Loss', '6大ロス分類'],
    ['Pilar OEE Terkait', '関連OEE要素'],
    ['Durasi (Jam)', '停止時間 (時間)'],
    ['% Kontribusi Loss', 'ロス比率 (%)'],
    ['ID Incident', 'インシデントID'],
    ['Jam Trouble', '発生時刻'],
    ['Mesin & Line', '設備・ライン'],
    ['Durasi (m)', '停止 (分)'],
    ['Akar Masalah (5 Whys RCA)', '根本原因 (5なぜ分析)'],
    ['Total Output Produksi', '総生産実績数'],
    ['Good Output (OK)', '良品数量 (OK)'],
    ['Total Reject / NG', '総不良数量 (NG)'],
    ['Defect Rate (%)', '不良率 (%)'],
    ['Quality Yield Rate (%)', '良品歩留まり率 (%)'],
    ['Wajib OEE (A/R/C)', '主要部品 (Assy/Rod/Cap)'],
    ['Pelengkap (B/Bs/N/P)', '締結部品 (Bolt/Bush/Nut/Pin)'],
    ['Masalah / Kategori Defect', '不良分類・現象'],
    ['Tindakan CAPA', '是正処置 (CAPA)'],
    ['Plan (m)', '計画 (分)'],
    ['Down (m)', '停止 (分)'],
    ['Speed (p/m)', '速度 (個/分)'],
    ['Defect (Pcs)', '不良 (個)'],
    ['Qual (%)', '品質 (%)'],
    ['Wajib OEE (Komponen Utama)', '主要部品 (OEE対象)'],
    ['Pelengkap Non-OEE', '付属部品 (非OEE)'],

    // 3. PAGE HEADINGS & SUB-SECTIONS
    ['Analisis Gangguan & Downtime Mesin', '設備トラブル及び停止ロス分析'],
    ['Analisis Cacat & Defect Produk (NG)', '品質不良及びNG分析'],
    ['Peringkat Efisiensi Sub-Asset Mesin (Machine Ranking)', '設備別 総合効率ランキング (Machine Ranking)'],
    ['Machine Performance', '設備別稼働実績'],
    ['List Data Produksi — Tanggal', '生産実績データ一覧 — 生産日'],
    ['Log Trouble & Downtime — Tanggal', 'トラブル・停止ログ一覧 — 生産日'],
    ['Komponen Utama (Wajib OEE) — Rincian Multi-Baris', '主要構成部品 (OEE対象) — 明細登録'],
    ['Komponen Pelengkap & Fasteners (Opsional)', '付属・締結部品 (非OEE・任意)'],
    ['Analisa Defect & Disposisi QC', '不良要因分析及びQC処置判定'],
    ['Shift Performance', '直別稼働実績 (シフト比較)'],
    ['Shift OEE & Pillars Comparative Metrics', '直別OEE及び3要素比較指標'],
    ['Diagram Pareto Penyebab Reject (Vital Few vs Useful Many)', '不良原因パレート図 (重点項目 vs その他)'],
    ['Proporsi Reject per Komponen', '部品別 不良発生比率'],
    ['Ranking Bagian NG Terbanyak (Defect Section Breakdown)', 'ワースト不良部位ランキング'],
    ['Matriks Top 10 Defect Reason & Rekomendasi Solusi Teknis', 'ワースト10不良要因マトリクス及び技術対策提案'],
    ['Gagal Memuat Analisis Pareto', 'パレート分析データの読み込みに失敗しました'],
    ['Reports & Export', '帳票・実績日報出力'],
    ['Tabel Rekapitulasi Rincian Data Defect & NG', '品質不良・NG集計実績テーブル'],
    ['Tabel Rekapitulasi Rincian Data Trouble & Downtime Mesin', '設備トラブル・停止履歴集計テーブル'],
    ['Speed & Output Telemetry', '速度・出来高テレメトリ'],
    ['Recorded Stoppages & Downtimes', '記録された設備停止・ダウンタイム'],
    ['Global OEE Target Thresholds', 'グローバルOEE目標閾値設定'],
    ['Production Floor TV Mode Settings', '現場大型TVモニター表示設定'],
    ['Preview Kop Laporan', '帳票レターヘッドプレビュー'],
    ['Upload Logo Perusahaan', '企業ロゴアップロード'],
    ['Informasi Legal & Operasional Pabrik', '工場基本情報及びレターヘッド設定'],
    ['Standar Baseline Target OEE (World Class TPM Metrics)', '基準目標OEE標準 (ワールドクラスTPM基準)'],
    ['Preferensi Antarmuka & Interval Auto-Refresh', '表示設定及び自動更新インターバル'],
    ['Gagal Mengambil Diagnostik Database', 'データベース診断情報の取得に失敗しました'],
    ['Manajemen Database & Pembersihan Go-Live', 'データベース管理及び本番稼働用初期化'],
    ['Pembersihan Data Massal untuk Persiapan Live (Go-Live Preparation)', '本番稼働に向けたテストデータの一括初期化'],
    ['Pembersihan Total Transaksi', '全トランザクションデータ初期化'],
    ['Tabel Data Transaksional', 'トランザクションデータテーブル'],
    ['Tabel Master & Konfigurasi', 'マスタ及び設定テーブル'],
    ['Total downtime & speed loss across 6 TPM pillars', 'TPM 6大ロスに基づく停止時間及び速度低下集計'],
    ['Top penyebab waktu henti mesin (Availability Losses)', 'ワースト設備停止要因 (時間稼働ロス)'],
    ['Top jenis cacat & Rekomendasi Tindakan Korektif', 'ワースト不良項目及び是正処置提案'],
    ['Ringkasan efisiensi dan output per lini produksi', 'ライン別 OEE効率及び出来高サマリー'],
    ['Daftar utilisasi seluruh unit mesin dan stasiun kerja', '全設備・ワークステーション稼働状況一覧'],
    ['Peringkat efisiensi OEE, ketersediaan mesin, kualitas, dan downtime per unit sub-asset.', '設備ごとのOEE効率、時間稼働率、良品率、停止時間ランキング'],
    ['Efisiensi OEE, ketersediaan, performa, mutu kualitas, dan produk yang diproduksi per lini produksi.', 'ライン別のOEE総合効率、時間稼働率、性能稼働率、良品率、及び生産製品一覧'],
    ['Realtime breakdown per tanggal produksi untuk masing-masing Shift', '生産日別・直別のリアルタイム実績内訳'],
    ['Distribusi frekuensi defect aktual (Batang Rose) & Kurva Kumulatif 80/20 (Garis Neon Cyan)', '不良発生件数 (棒グラフ) 及び 80/20累積パレート曲線 (折れ線)'],
    ['Distribusi produk cacat antara Assy, Rod, Cap & Fasteners', 'Assy、Rod、Cap、締結部品別の不良分布'],
    ['Area anatomi komponen manufaktur yang paling sering mengalami defect', '不良が最も多発している部品部位・箇所'],
    ['Analisis prioritas perbaikan continuous improvement berbasis prinsip Kaizen & Six Sigma', 'カイゼン及びシックスシグマに基づく重点改善項目の分析'],
    ['Tidak ada catatan kendala mesin melebihi 5 menit pada rentang waktu ini. Lini beroperasi optimal.', '対象期間中に5分以上の設備停止記録はありません。正常稼働しています。'],
    ['Daftar item NG per lini, mesin, jenis defect wajib OEE & pelengkap non-OEE beserta tindakan CAPA', 'ライン別、設備別、OEE対象部品及び非OEE部品のNG明細一覧 (CAPA是正処置付き)'],
    ['Daftar seluruh kendala teknis, waktu henti, analisa root cause, dan tindakan perbaikan (CAPA) tersinkron otomatis dari data harian produksi.', '生産日報から自動集計された技術トラブル、停止時間、根本原因分析、及び是正処置 (CAPA) 一覧'],
    ['Master data terproteksi permanen dan tidak akan tersentuh saat pembersihan.', 'マスタデータは完全に保護されており、データ初期化時も削除されません。'],
    ['Tabel yang berisi riwayat aktivitas dan dapat dibersihkan untuk Go-Live.', '本番稼働前に初期化可能な実績履歴テーブルです。'],
    ['Bersihkan data uji coba / simulasi agar aplikasi bersih dan siap digunakan secara resmi oleh operator & supervisor lini.', 'テスト・検証用データを削除し、現場オペレーター及び管理者向けに正式運用を開始できる状態にします。'],
    ['Hanya membersihkan tabel record produksi harian, snapshot kalkulasi OEE (A/P/Q), dan ringkasan shift.', '生産実績レコード、OEE計算スナップショット(A/P/Q)、直集計テーブルのみを初期化します。'],
    ['Hanya membersihkan riwayat pencatatan breakdown mesin, kendala perbaikan, dan deskripsi CAPA.', '設備停止履歴、修繕記録、及びCAPA是正処置履歴のみを初期化します。'],
    ['Hanya membersihkan antrean laporan NG, rincian item reject part, dan catatan sampling QC.', 'NG報告キュー、不良部品明細、及びQCサンプリング記録のみを初期化します。'],
    ['Bersihkan seluruh record hasil produksi, kalkulasi OEE, trouble log downtime, dan defect NG.', '全生産実績、OEE計算値、設備停止ログ、及び不良NGデータをすべて初期化します。'],
    ['Master Data Shield: Aktif & Terproteksi', 'マスタデータ保護シールド: 有効 (完全保護)'],
    ['REKOMENDASI GO-LIVE', '本番稼働前 推奨設定'],
    ['TRANSAKSI', 'トランザクション'],
    ['🔒 TERPROTEKSI', '🔒 保護対象'],
    ['AMAN', '安全'],
    ['BERSIHKAN', '初期化実行'],
    ['Total Laporan Terkena NG:', '不良発生日報数:'],
    ['Terverifikasi / Pending', '確認済 / 未確認'],
    ['Dominant Component', '最多不良部品'],
    ['Quality Yield & PPM', '良品歩留まり率及びPPM'],
    ['TANGGAL AUDIT:', '監査日:'],
    ['Total Kejadian Trouble', '総トラブル発生件数'],
    ['Total Durasi Waktu Henti', '総設備停止時間'],
    ['Rata-Rata Penanganan (MTTR)', '平均復旧時間 (MTTR)'],
    ['Mesin Paling Terkendala', 'ワースト停止設備'],
    ['Line OEE Score:', 'ラインOEEスコア:'],
    ['ATTENTION: STOPPED / BREAKDOWN MACHINES', '警告: 停止中・故障中の設備'],
    ['NEEDS IMMEDIATE ACTION', '即時対応が必要'],
    ['REAL-TIME PREVIEW', 'リアルタイム プレビュー'],
    ['Logo Aktif Terpasang', '登録済みロゴ'],
    ['Logo Siap Disimpan', '保存可能なロゴ'],
    ['Database Engine', 'データベースエンジン'],
    ['Storage & Capacity', 'ストレージ及び使用容量'],
    ['Server Runtime', 'サーバー実行環境'],
    ['Search machine, line, SKU...', '設備、ライン、品番(SKU)で検索...'],
    ['Cari kode/nama mesin...', '設備コード/設備名で検索...'],
    ['Search records...', 'レコード検索...'],
    ['Penyebab Downtime', '停止要因'],
    ['Durasi', '停止時間'],
    ['Kontribusi', '寄与率・比率'],
    ['Jenis Defect', '不良現象・種類'],
    ['Bagian', '部位・箇所'],
    ['Volume', '数量'],
    ['Rekomendasi Kaizen', 'カイゼン・是正提案'],
    ['Availability', '時間稼働率'],
    ['Performance', '性能稼働率'],
    ['Quality', '良品率'],
    ['Output Aktual', '実績出来高'],
    ['Code', 'コード'],
    ['Machine Name', '設備名'],
    ['Line', 'ライン'],
    ['Actual', '実績'],
    ['Rejects', '不良品'],
    ['Downtime', '停止時間'],
    ['Product Name', '製品名'],
    ['Shift', '直 (シフト)'],
    ['Measuring', '実測数'],
    ['NG Qty', '不良数'],
    ['Reject Rate', '不良率'],
    ['OEE Score', 'OEEスコア'],
    ['Waktu Trouble', '発生時刻'],
    ['Line & Mesin', 'ライン・設備'],
    ['Shift & Team', '直・班'],
    ['Product', '製品'],
    ['Jenis Problem', '問題分類'],
    ['Masalah / Kendala (Trouble)', 'トラブル内容・症状'],
    ['Line ID', 'ラインID'],
    ['Line Name', 'ライン名'],
    ['Machine', '設備'],
    ['Product SKU', '製品型番 (SKU)'],
    ['Avail', '稼働'],
    ['Perf', '性能'],
    ['Defect', '不良'],
    ['Qual', '品質'],
    ['Jam', '時間'],
    ['Laporan', '件']
];

// Extract existing dictionary
const dictRegex = /const MONOZUKURI_MASTER_DICTIONARY = (\[[\s\S]*?\]);/;
const match = content.match(dictRegex);
if (!match) {
    console.error('Could not find MONOZUKURI_MASTER_DICTIONARY');
    process.exit(1);
}

const existing = eval(match[1]);
const existingKeys = new Set(existing.map(x => x[0]));

let addedCount = 0;
newEntries.forEach(([from, to]) => {
    if (!existingKeys.has(from)) {
        existing.push([from, to]);
        existingKeys.add(from);
        addedCount++;
    }
});

// Format back to string
const newDictStr = 'const MONOZUKURI_MASTER_DICTIONARY = ' + JSON.stringify(existing, null, 4) + ';';
content = content.replace(dictRegex, newDictStr);

fs.writeFileSync(i18nPath, content, 'utf8');
console.log('Successfully added', addedCount, 'new entries to MONOZUKURI_MASTER_DICTIONARY!');
console.log('Total entries in MONOZUKURI_MASTER_DICTIONARY now:', existing.length);
